googlefonts/picosvg

src/picosvg/svg.py
src/picosvg/svg_types.py
tests/matrix-before.svg
tests/matrix-nano.svg
tests/svg_test.py

Fix bug where matrix directly on shape got lost

Test a direct matrix

---

src/picosvg/svg.py
src/picosvg/svg_reuse.py
tests/svg_reuse_test.py

Rudimentary ability to identify shapes for reuse

Shape reuse

---

.travis.yml
src/picosvg/svg.py
src/picosvg/svg_meta.py
src/picosvg/svg_pathops.py
src/picosvg/svg_reuse.py
src/picosvg/svg_types.py
tests/svg_pathops_test.py

Fix circular dependency issue

---

src/picosvg/svg.py
tests/ungroup-before.svg

Drop group enable-background; it is deprecated

---

src/picosvg/svg.py
src/picosvg/svg_meta.py
src/picosvg/svg_types.py
tests/svg_test.py

Early steps toward surviving some of the weirdness in Noto gradients (weird gradient coords + transforms) better.
Move parsing logic nanoemoji => picosvg to enable.
Fixes #127

Preprocess gradientTransform translation

---

src/picosvg/svg.py
tests/svg_test.py

Fix div 0 issue when extracting translate from a gradient transform

---

src/picosvg/svg.py
src/picosvg/svg_types.py
tests/stroke-fill-opacity-after.svg
tests/stroke-fill-opacity-before.svg
tests/svg_test.py
tests/svg_types_test.py

Fixes https://github.com/googlefonts/picosvg/issues/142

Add support for fill-opacity

---

src/picosvg/svg.py
tests/bad-ids-1.svg
tests/stroke-with-id-before.svg
tests/stroke-with-id-nano.svg
tests/svg_test.py
tests/ungroup-with-ids-before.svg
tests/ungroup-with-ids-nano.svg

Fixes #165 
Built on top of #163

Try harder not to duplicate ids

---

src/picosvg/svg_pathops.py
src/picosvg/svg_types.py
tests/invisible-after.svg
tests/invisible-before.svg
tests/invisible-nano.svg
tests/stroke-simplepath-after.svg
tests/svg_pathops_test.py
tests/svg_types_test.py

Remove filled paths with zero area or stroked paths with zero stroke-width

---

src/picosvg/svg.py
tests/drop-title-after.svg
tests/drop-title-before.svg
tests/svg_test.py

Usually, SVG files exported by design software will have title elements, this PR will be automatically deleted.

Drop <title>

---

src/picosvg/svg.py
tests/drop-title-after.svg
tests/drop-title-before.svg
tests/svg_test.py

Reverts googlefonts/picosvg#173

Revert "Drop <title>"

---

README.md

Reference: https://googlefonts.github.io/python

Add test doc

---

src/picosvg/picosvg.py

Needed to fix https://github.com/googlefonts/nanoemoji/pull/240

add --output_file flag

---

src/picosvg/svg_transform.py
tests/svg_transform_test.py

Fixes (again) the Vatical flag :)

strip leading/trailing space in parse_svg_transform

---

README.md
setup.py

https://pypi.org/project/pytest-clarity/
See also: https://darrenburns.net/posts/pytest-clarity-notes/

Add pytest-clarity, improving the readability of pytest output (with colour)

---

src/picosvg/geometric_types.py
src/picosvg/svg.py
src/picosvg/svg_meta.py
src/picosvg/svg_types.py
tests/no-viewbox-nano.svg
tests/svg_test.py
tests/svg_types_test.py
tests/transform-linear-objectbbox-nano.svg
tests/transform-radial-objectbbox-nano.svg
tests/transform-radial-userspaceonuse-nano.svg

Fixes #226
(note the base branch is `ungroup`, not `main`)

Convert "objectBoundingBox" to "userSpaceOnUse" before transforming gradients

---

src/picosvg/svg_transform.py
tests/svg_transform_test.py

make DECOMPOSITION_ALMOST_EQUAL_TOLERANCE more tolerant

---

src/picosvg/svg.py
tests/display_none-before.svg
tests/display_none-nano.svg
tests/svg_test.py

Make parent display=none override child display values

---

src/picosvg/svg_reuse.py
tests/svg_reuse_test.py

Does this make sense to you?
Fixes https://github.com/googlefonts/picosvg/issues/266.

Exploratory fix for arc normalization

---

src/picosvg/svg_meta.py
tests/svg_test.py

Allow vendor style pass through

---

.github/workflows/ci.yml

https://github.com/googlefonts/ufo2ft/blob/main/.github/workflows/ci.yml

ci.yml went stale, update based on ufo2ft
