src/nanosvg/arc_to_cubic.py
src/nanosvg/svg_types.py
tests/arc_to_cubic_test.py
tests/svg_types_test.py

The code is adapted with slight modifications from FontTools [fontTools/svgLib/path/arc.py](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/svgLib/path/arc.py), which in turn is adapted from Blink's [SVGPathNormalizer::DecomposeArcToCubic](https://github.com/chromium/chromium/blob/93831f2/third_party/blink/renderer/core/svg/svg_path_parser.cc#L169-L278).
The intention is to use this when doing tonanosvg(), and before converting svg to SkPath, but this is not hooked up yet in here.

re-add module to convert arcs to cubic beziers

---

src/picosvg/svg.py
tests/ungroup-after.svg
tests/ungroup-before.svg

otherwise implicit group from a <use overflow="visible"/> gets angry.
Fixes #27.

Drop default overflow on group

---

src/picosvg/geometric_types.py
src/picosvg/svg.py
src/picosvg/svg_transform.py
src/picosvg/svg_types.py
tests/degenerate-before.svg
tests/degenerate-nano.svg
tests/svg_test.py
tests/svg_transform_test.py
tests/svg_types_test.py

Trying to define ops with degenerate cases in ways that aren't raise an error.

Avoid crashing where a sane alternative exists

---

src/picosvg/svg.py
src/picosvg/svg_meta.py
src/picosvg/svg_types.py
tests/inline-css-style-after.svg
tests/inline-css-style-before.svg
tests/inline-css-style-nano.svg
tests/svg_test.py
tests/svg_types_test.py

Fixes https://github.com/googlefonts/picosvg/issues/59
SVG elements can have a `style` attribute containing a string formatted as CSS declaration list.
https://www.w3.org/TR/SVG/styling.html#ElementSpecificStyling
In noto-emoji's emoji_u1f469_1f3fd_200d_1f33e.svg and others, this is used in several SVG shapes, in the root svg element and in the linear and radial gradients' stop-colors.
In this PR, we parse these `style` attributes and replace them with the equivalent SVG element attributes upon converting to picosvg.
SVGShape dataclasses gain a new 'style' attribute so we can parse and retain that if needed. The `SVGShape.apply_style_attribute()` method will parse the embedded CSS declarations and convert them to equivalent SVG element attributes, leaving the style attribute itself empty …

add support for inline element-specific CSS style attributes

---

src/picosvg/svg.py
tests/svg_test.py

Very small values don't work out all that well.
Fixes picosvg for quite a lot of Noto Emoji; https://github.com/googlefonts/color-fonts/issues/10#issuecomment-725838351

Round gradient transforms avoid imprecision

---

src/picosvg/svg.py
tests/drop-anon-symbols-after.svg
tests/drop-anon-symbols-before.svg
tests/svg_test.py

Reduces the need to support symbol (#46). Merge after #133 (built on top). Helps with https://github.com/googlefonts/color-fonts/issues/10#issuecomment-725838351.

Drop anonymous <symbol>

---

tests/svg_reuse_test.py

Capture test; actual fix anticipated via nanoemoji flag default

Add test showing tolerance 0.1 => 0.2 making affine_between possible

---

src/picosvg/svg_types.py
tests/invisible-before.svg
tests/svg_types_test.py

Fixes noto-emoji/svg/emoji_u1f479.svg containing an invisible path that should not be painted
Before:
After:

SVGShape::might_paint() return False if display=none

---

src/picosvg/geometric_types.py
src/picosvg/svg.py
src/picosvg/svg_types.py
tests/outside-viewbox-clipped.svg
tests/outside-viewbox.svg
tests/svg_test.py

If entirely outside, goodbye. If partially outside, clipped. Does not attempt to resolve transforms, etc; just destroys content outside. Presumed typical use is to convert to picosvg and only then clip to viewbox.
Meant to power https://github.com/googlefonts/nanoemoji/issues/200.

Add an API to destroy content outside the viewbox

---

src/picosvg/svg.py
tests/svg_test.py
tests/svg_test_helpers.py

Avoid replacing the default when an attribute is blank to prevent issues like https://github.com/googlefonts/nanoemoji/issues/229.

Don't apply blank attributes

---

src/picosvg/svg.py
tests/svg_test.py
tests/ungroup-transform-after.svg
tests/ungroup-transform-before.svg
tests/ungroup-transform-nano.svg

When we remove `<g>` elements and matrix-multiply a parent group's transform with a child's own transform, if the result is identity (the two transforms cancel out each other) then we need to ensure we delete the transform attribute on the child element (so it will default to identity). Otherwise things get messed up, e.g. noto-emoji/third_party/region-flags/svg/SV.svg
before:
after:

fix un-grouping when inherited transform == identity

---

src/picosvg/geometric_types.py
src/picosvg/svg.py
src/picosvg/svg_transform.py
tests/svg_transform_test.py

Needed in nanoemoji to fix https://github.com/googlefonts/nanoemoji/issues/243
when mapping SVG radial gradients to font space in nanoemoji, we want to pre-apply as much transform as we can to the gradient geometry, thus we need to extract the scale and translation components from an Affine2D.
This PR adds a decompose_scale (copied from SkMatrix) and a decompose_translation (mutuated from Rod's code used for apply gradient translation).

svg_transform: add decompose_scale and decompose_translation

---

src/picosvg/svg.py
tests/gradient-template-1-before.svg

One noto-emoji region flag (TA.svg) contain useless id attributes for all elements, including `<stop>` ones. When we resolve gradient templates, we copy the stop elements from the template but then we incur in a fatal picosvg violation as we end up with non-unique ids. We can simply strip the stop id attributes as they don't have any use.

strip id when copying stop from gradient template

---

src/picosvg/svg.py
tests/drop-title-meta-desc-before.svg

namely the Puertorican flag (PR.svg)
More info on the old comment tag https://html.com/tags/old-comment-tag/
(btw, I'm getting there, just 4 flags to go..)

some flags contain the old HTML <comment> elements, strip that too

---

src/picosvg/svg_types.py
tests/svg_types_test.py

currently we do:
https://github.com/googlefonts/picosvg/blob/9d00851d8bc25616116836f826e3d7089492312f/src/picosvg/svg_types.py#L842
But the [SVG spec](https://www.w3.org/TR/SVG2/coords.html#Units) says
> For any other length value expressed as a percentage of the SVG viewport, the percentage must be calculated as a percentage of the normalized diagonal of the ‘viewBox’ applied to that viewport. If no ‘viewBox’ is specified, then the normalized diagonal of the SVG viewport must be used. The normalized diagonal length must be calculated with sqrt((width)**2 + (height)**2)/sqrt(2).
So we should do the right thing (even if percentages usually are used with objectBoundingBox where the unit square by definition is width==height==1).
I push the failing test first, then the fix

parse radialGradient radius as percentage of viewport diagonal, not width

---

src/picosvg/svg.py
src/picosvg/svg_transform.py
tests/svg_transform_test.py

The product staticmethod is wrong, instead of matrix-multiplying first x second, it was doing the opposite, second x first.
This PR adds `__matmul__` infix operator ('@') for correct matrix multiplication, and deprecates the old incorrect product() method, temporarily kept only for backward compatibility

Affine2D: define __matmul__ infix operator; deprecate product()

---

src/picosvg/svg.py
tests/fill-rule-evenodd-after.svg
tests/svg_test.py

currently `evenodd_to_nonzero_winding` method fails if `shapes_to_paths` is not called first. That's because `remove_overlaps` method is only defined on `SVGPath` class, not on the rest of the SVGShapes.
Sometimes one may want to be able to only run `evenodd_to_nonzero_winding` without applying the rest of the topicosvg filters.
This patch allows to do that, by first calling `SVGShape.as_path()` and then `remove_overlaps`.

allow to run evenodd_to_nonzero_winding method in isolation

---

src/picosvg/svg_transform.py
tests/svg_transform_test.py

While debugging googlefonts/nanoemoji#339 (comment), I stumbled on an affine `(0, -2.875, 2.875, 0, 2.39, 250.81)` whose inverse, when combined with self, did not give me back identity..
I was expecting the inverse to be (0.0, 0.348, -0.348, 0.0, 87.238, -0.831), whereas I was getting (0.0, 0.348, -0.348, 0.0, 87.238, -30.344).
It turned out the Affine2D.inverse() method was incorrectly computing its `dy` (or `f`) component for the inverse matrix.
The local variable `e` was being reassigned, thus influencing the calculation of `f` in the following statement. 
The fix itself explains better than any words:
```diff
diff --git a/src/picosvg/svg_transform.py b/src/picosvg/svg_transform.py
index 5e519bf..f2664ef 100644
--- a/src/picosvg/svg_transform.py
+++ b/src/picosvg/svg_transform.py
@@ …
```

fix incorrect inverse affine transform dy component

---

reuse_example.html
src/picosvg/svg_reuse.py
tests/svg_reuse_test.py

Normalizing to a set of 0's isn't all that helpful. This could occur when the initial drawing command did not move away from the first move, e.g. `M 1,1 L 1,1`.

Fix problem where reuse was normalizing to 0's

---

src/picosvg/svg_types.py
tests/svg_types_test.py

When splitting SVGPath into subpaths, we must ensure each subpath's coordinates are independent from the preceding ones. If an empty subpath containing only a moveto is followed by a non-empty one that starts with a relative moveto ('m'), removing the empty subpath without adjusting the relative moveto produces an incorrect result (as shown in the noto-emoji "foot" => https://github.com/googlefonts/picosvg/issues/252#issuecomment-1026839746).
We could call SVGPath.absolute() and then split into subpaths() in order to remove_empty_subpaths() -- inside topicosvg() method, the former occurs after the latter --, but it's preferable that we keep each logically distinct opeartion self-contained and handle relative moveto correctly when we split the subpaths, by making only the first moveto …

make subpath moveto absolute before removing empty ones

---

src/picosvg/svg_reuse.py
src/picosvg/svg_types.py
tests/svg_reuse_test.py

We commonly encounter this in real inputs.
Helps with #271. **Not** as fixing that issue because this only handles the specific subset of the general problem we're actually seeing in practice.

Upgrade arc handling to support circles and ellipses formed of two arcs

---

setup.py
src/picosvg/svg_reuse.py
tests/svg_reuse_test.py

This fixes #278, see discussion there.
The proposed fix is likely not the optimal one – I am happy to change it.
@anthrotype

fix: line_length assertion error for odd paths

---

src/picosvg/svg_pathops.py
src/picosvg/svg_types.py
tests/svg_pathops_test.py

Add the ability to diff

---

.gitignore
src/picosvg/svg.py
tests/svg_test.py
tests/xpacket.svg

- Abstracted out "check if tag is a comment" into _is_redundant(tag).
- Added etree.ProcessingInstruction to the set of redundant tags.
- Created function to remove processing instructions.
- Changed topicosvg to remove processing instructions.
- Added test to ensure xpacket tags no longer break picosvg, and are
actually removed when topicosvg is called.

Made picosvg ignore <?xpacket?> tags.

---

src/picosvg/picosvg.py
src/picosvg/svg.py
tests/svg_test.py
tests/text-before.svg

- Added `allow_text` options to both `topicosvg()` and `checkpicosvg()`to enable simplifying SVGs with text elements. Note that the text elements will not be converted to paths, they will only pass through.
- Added an `allow_text` boolean flag to the command line tool to control this behaviour.

Made text elements optionally allowed

---

src/picosvg/picosvg.py
src/picosvg/svg.py
tests/comments-before.svg
tests/comments-image-style-before.svg
tests/comments-image-style-nano.svg
tests/comments-nano.svg
tests/svg_test.py

If `--drop_unsupported` is set picosvg will drop the element instead of failing and reporting BadElement. Fixes #297. 
For context, this is not a capability I wanted for our usage but since we now have some evidence people are rolling their own equivalent maybe we should just support it directly.
```shell
$ picosvg /tmp/uni7cb9.svg
blah blah blah
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/style[0],BadElement: /svg[0]/image[0]
$ picosvg --drop_unsupported /tmp/uni7cb9.svg
(works)
```
~~EDIT: I believe the test failure is https://github.com/googlefonts/picosvg/issues/299 and not due to this PR~~ Fixed

Exploratory optional discard of all unsupported elements

---

src/picosvg/svg.py
tests/svg_test.py

Fixes Attribute error when attempting to remove comments with inplace=True and the comment has no parents.
Using the XMLParser(remove_comments=True) option does the trick
Fixes https://github.com/googlefonts/picosvg/issues/297

use XMLParser with remove_comments=True
